export const INIT_GET_LIST_DATA = "INIT_GET_LIST_DATA"
export const FETCH__GET_LIST_DATA = "FETCH_GET_LIST_DATA"
export const FETCHING__GET_LIST_DATA_SUCCESSFUL = "FETCHING__GET_LIST_DATA_SUCCESSFUL"
export const FETCHING__GET_LIST_DATA_FAILED = "FETCHING__GET_LIST_DATA_FAILED"

export const UPDATE__CUSTOMER_DATA = "UPDATE__CUSTOMER_DATA"
export const UPDATE__CUSTOMER_DATA_SUCCESSFUL = "UPDATE__CUSTOMER_DATA_SUCCESSFUL"
export const UPDATE__CUSTOMER_DATA_FAILED = "UPDATE__CUSTOMER_DATA_FAILED"

export const DELETE__CUSTOMER_DATA = "DELETE__CUSTOMER_DATA"
export const DELETE__CUSTOMER_DATA_SUCCESSFUL = "DELETE__CUSTOMER_DATA_SUCCESSFUL"
export const DELETE__CUSTOMER_DATA_FAILED = "DELETE__CUSTOMER_DATA_FAILED"